networks:
  rugram:
    name: rugram_default
services:
  Gateway:
    container_name: Gateway
    image: rugramgateway
    ports:
      - "3001:80"
    restart: always
    build:
      context: .RugramBackend/Gateway
      dockerfile: /Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - AuthOptions__Issuer=RugramAuth
      - AuthOptions__Audience=Rugram
      - AuthOptions__JwtSecretKey=123
      - AuthOptions__AccessTokenLifetimeInMinutes=2
      - Microservices__AuthAddress=https://auth:7057
    networks:
      rugram:
        aliases:
          - gateway
  auth:
    container_name: auth
    image: rugramauth
    restart: always
    build:
      context: .RugramBackend/Gateway
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - AuthOptions__Issuer=RugramAuth
      - AuthOptions__Audience=Rugram
      - AuthOptions__JwtSecretKey=123
      - AuthOptions__AccessTokenLifetimeInMinutes=2
      - AuthOptions__RefreshTokenLifetimeInHours=168
      - Cache__SlidingExpirationForRefreshTokenInMinutes=5
      - MailConfirmationToken__LifetimeInHours=24
      - EmailConfig__Sender=alinaagro@inbox.ru
      - EmailConfig__SenderName=RugramES
      - EmailConfig__SenderPassword=RugramES
      - SmtpSettings__Port=587
      - SmtpSettings__SmtpAddress=smtp.mail.ru
      - Domain__AppUrl=http://localhost:3001
      - ConnectionStrings__PostreSQL=Server=dbAuth;Port=5432;Database=RugramAuth;User Id=dev;Password=111;Include Error Detail=true;
      - ConnectionStrings__Redis=redisAuth:6379,password=111
    depends_on:
      - DbAuth
      - RedisAuth
    networks:
      rugram:
        aliases:
          - auth
  RedisAuth:
    container_name: RedisAuth
    image: redis:6.2-alpine
    restart: always
    command: redis-server --save 20 1 --loglevel warning --requirepass 111
    networks:
      rugram:
        aliases:
          - redisAuth
  DbAuth:
    container_name: DbAuth
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: 111
      POSTGRES_DB: RugramAuth
    networks:
      rugram:
        aliases:
          - dbAuth