networks:
  rugram:
    name: rugram_default
services:
  Gateway:
    container_name: Gateway
    image: rugramgateway
    ports:
      - "3001:443"
    restart: always
    build:
      context: RugramBackend/Gateway
      dockerfile: /Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${KestrelCertifyPass}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - AuthOptions__Issuer=RugramAuth
      - AuthOptions__Audience=Rugram
      - AuthOptions__JwtSecretKey=${JwtSecretKey}
      - AuthOptions__AccessTokenLifetimeInMinutes=2
      - Microservices__AuthAddress=http://auth:80
    networks:
      rugram:
        aliases:
          - gateway
  Auth:
    container_name: Auth
    image: rugramauth
    restart: always
    build:
      context: RugramBackend/Gateway
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - AuthOptions__Issuer=RugramAuthd
      - AuthOptions__Audience=Rugram
      - AuthOptions__JwtSecretKey=${JwtSecretKey}
      - AuthOptions__AccessTokenLifetimeInMinutes=2
      - AuthOptions__RefreshTokenLifetimeInHours=168
      - Cache__SlidingExpirationForRefreshTokenInMinutes=5
      - MailConfirmationToken__LifetimeInHours=24
      - EmailConfig__Sender=alinaagro@inbox.ru
      - EmailConfig__SenderName=RugramES
      - EmailConfig__SenderPassword=${EmailSenderPassword}
      - SmtpSettings__Port=587
      - SmtpSettings__SmtpAddress=smtp.mail.ru
      - Domain__AppUrl=https://localhost:3010
      - ConnectionStrings__PostreSQL=${AuthConnectionStringPostreSQL}
      - ConnectionStrings__Redis=redisAuth:6379,password=${AuthRedisPassword}
    depends_on:
      - DbAuth
      - RedisAuth
    networks:
      rugram:
        aliases:
          - auth
  RedisAuth:
    container_name: RedisAuth
    image: redis:7.2.3-alpine3.18
    restart: always
    command: redis-server --save 20 1 --loglevel warning --requirepass ${AuthRedisPassword}
    ports:
      - "3002:6379"
    networks:
      rugram:
        aliases:
          - redisAuth
  DbAuth:
    container_name: DbAuth
    image: postgres:16.0-alpine3.18
    restart: always
    ports:
      - "3003:5432"
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: ${DbAuthPassword}
      POSTGRES_DB: RugramAuth
    networks:
      rugram:
        aliases:
          - dbAuth